version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
              - dbt_expectations.expect_column_distinct_values_to_be_in_set:
                  value_set: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_not_match_regex:
                  regex: "^\\$[0-9][0-9\\.]+$"
              # - dbt_expectations.expect_column_min_to_be_between:
              #     min_value: 0
              #     max_value: 50
              # - dbt_expectations.expect_column_max_to_be_between:
              #     min_value: 500
              #     max_value: 10000
       


      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}